### ISSUE TITLE
Extension leaves dozens of *flycheck.tmp.co.pl files in source directory

### ISSUE THREAD

**Issue by tj800x** [ciao-lang/ciao_vsc#1]
As the title says, this extensions leaves dozens of *flycheck.tmp.co.pl files in source directory.  
These should be created in the users temp directory if possible.

**Comment by mciccale** [comment]
Hi Tom! Thanks for the report.

The generation of temporary / auxiliary files in the source directory is not directly caused by the extension. This situation has to do with Ciao, which at the moment needs these temporary files to be in the same directory (for various reasons). However, we know that it may feel a bit messy.

We will take a look at it!

**Comment by tj800x** [comment]
I figured that it wasn't an easy fix. It's something I am finding interferes with my workflow to the degree that I probably cannot ignore it.

**Comment by mciccale** [comment]
I understand, we are already working on a short-term solution for it from the extension side until we figure out how to prevent this behavior from the language side.

Sorry for the inconvenience.

**Comment by mciccale** [comment]
Hey Tom, a quick update. We've already published in the VS Code marketplace a new version of the extension that removes the temporary files (`*_flycheck_tmp_co.pl`) immediately after they are created. This should improve your workflow experience, please tell us if that's the case so we can close this issue!

Thanks!

**Comment by tj800x** [comment]
Great!  The files don't seem to persist.  Thank you for the quick response.
